---
language: node_js
node_js:
  - "10"

dist: xenial

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master

script:
  - npm run lint:js
  - npm test
  - npm run build -- -prod # build app and prepare dist folder


# deploy master branch to GitHub pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: fd3b85b48316e1c0d9d04b5a5bbfd7a985e5590a
  keep-history: true
  on:
    branch: master
  local-dir: dist
  verbose: true
